### PR TITLE
Optional duration filter

### PR DESCRIPTION
**Pull request by MiniGod**
PR for #6 

I added an optional parameter to `findBestMusicVideo`, so the API is now  
`#findBestMusicVideo(title, [duration], callback)`  
`duration` is in `ms`

example:

``` javascript
youtubeBestVideo.findBestMusicVideo('keeno moonrise', 408685, console.log)
```

---

I took the liberty of having the score from 0 to 5 instead of 0 to 1 like the other filters. I did some tests and a max score of 1 never bumped the song i wanted to the top.

### CODE REVIEW

**Comment by MaxGfeller** [comment]
Looks good to me! However, wouldn't it make more sense to have the duration in seconds?

**Comment by MiniGod** [comment]
I think not. Everything in javascript is `ms`. Also, YouTube and Spotify return duration with up to 3 decimals, ie `ms` precision.

**Comment by MaxGfeller** [comment]
Alright, merged and released in 0.0.8

**Comment by MaxGfeller** [comment]
Thanks!

**Pull request merged**
